# Generated by Django 2.1.2 on 2018-10-19 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_tag', message='Tag must consist of lowercase letters, digits and hyphens.', regex='^[a-z][a-z0-9\\-]*$')]),
        ),
    ]
