# Generated by Django 2.1.2 on 2018-10-20 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181019_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='natural-regulators', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must consist of lowercase letters, digits and hyphens.', regex='^[a-z][a-z0-9\\-]*$')]),
            preserve_default=False,
        ),
    ]
