# Generated by Django 2.1.2 on 2018-10-21 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('file', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.SlugField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', inverse_match=True, message="Name is reserved: 'new', 'edit' or 'test'.", regex='^(?:new|edit|test)*$')]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.SlugField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_tag', message='Tag must consist of lowercase letters, digits and hyphens.', regex='^[a-z]+(?:-[a-z0-9]+)*$')]),
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(to='posts.Image'),
        ),
    ]
