# Generated by Django 2.1.2 on 2018-10-22 00:07

from django.db import migrations, models
import posts.utils


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20181022_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='filename',
            field=models.CharField(default='foo', max_length=30, unique=True, validators=[posts.utils.FileValidator(allowed_extensions=('jpg', 'png', 'svg'), allowed_mimetypes=('image/jpg', 'image/png', 'image/svg'), restricted_basename=True)]),
            preserve_default=False,
        ),
    ]
