# Generated by Django 2.1.2 on 2018-10-22 01:46

from django.db import migrations, models
import posts.utils


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20181022_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(unique=True, upload_to='img/%Y%m/', validators=[posts.utils.FileValidator(allowed_extensions=('jpg', 'png', 'svg'), allowed_mimetypes=('image/jpg', 'image/png', 'image/svg'), restricted_basename=True)]),
        ),
    ]
