# Generated by Django 2.1.2 on 2018-10-24 02:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='filename',
            field=models.CharField(default='l1_l2_priors.png', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', inverse_match=True, message="Name is reserved: 'new', 'edit' or 'test'.", regex='^(?:new|edit|test)*$')]),
            preserve_default=False,
        ),
    ]
