# Generated by Django 2.1.2 on 2018-11-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20181031_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post_id',
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(to='posts.Image'),
        ),
    ]
