# Generated by Django 2.1.2 on 2018-11-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20181102_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
